local FlagsTable = {
    {img = love.graphics.newImage('flags/afghanistan.png'), name = 'Afghanistan'},
    {img = love.graphics.newImage('flags/albania.png'), name = 'Albania'},
    {img = love.graphics.newImage('flags/algeria.png'), name = 'Algeria'},
    {img = love.graphics.newImage('flags/andorra.png'), name = 'Andorra'},
    {img = love.graphics.newImage('flags/angola.png'), name = 'Angola'},
    {img = love.graphics.newImage('flags/antiguaandbarbuda.png'), name = 'Antigua and Barbuda'},
    {img = love.graphics.newImage('flags/argentina.png'), name = 'Argentina'},
    {img = love.graphics.newImage('flags/armenia.png'), name = 'Armenia'},
    {img = love.graphics.newImage('flags/australia.png'), name = 'Australia'},
    {img = love.graphics.newImage('flags/azerbaijan.png'), name = 'Azerbaijan'},
    {img = love.graphics.newImage('flags/bahamas.png'), name = 'Bahamas'},
    {img = love.graphics.newImage('flags/bahrain.png'), name = 'Bahrain'},
    {img = love.graphics.newImage('flags/bangladesh.png'), name = 'Bangladesh'},
    {img = love.graphics.newImage('flags/barbados.png'), name = 'Barbados'},
    {img = love.graphics.newImage('flags/belarus.png'), name = 'Belarus'},
    {img = love.graphics.newImage('flags/belgium.png'), name = 'Belgium'},
    {img = love.graphics.newImage('flags/belize.png'), name = 'Belize'},
    {img = love.graphics.newImage('flags/benin.png'), name = 'Benin'},
    {img = love.graphics.newImage('flags/bhutan.png'), name = 'Bhutan'},
    {img = love.graphics.newImage('flags/bolivia.png'), name = 'Bolivia'},
    {img = love.graphics.newImage('flags/bosniaandherzegovina.png'), name = 'Bosnia and Herzegovina'},
    {img = love.graphics.newImage('flags/botswana.png'), name = 'Botswana'},
    {img = love.graphics.newImage('flags/brazil.png'), name = 'Brazil'},
    {img = love.graphics.newImage('flags/brunei.png'), name = 'Brunei'},
    {img = love.graphics.newImage('flags/bulgaria.png'), name = 'Bulgaria'},
    {img = love.graphics.newImage('flags/burkinafaso.png'), name = 'Burkina Faso'},
    {img = love.graphics.newImage('flags/burundi.png'), name = 'Burundi'},
    {img = love.graphics.newImage('flags/caboverde.png'), name = 'Cabo Verde'},
    {img = love.graphics.newImage('flags/cambodia.png'), name = 'Cambodia'},
    {img = love.graphics.newImage('flags/cameroon.png'), name = 'Cameroon'},
    {img = love.graphics.newImage('flags/canada.png'), name = 'Canada'},
    {img = love.graphics.newImage('flags/centralafricanrepublic.png'), name = 'Central African Republic'},
    {img = love.graphics.newImage('flags/chad.png'), name = 'Chad'},
    {img = love.graphics.newImage('flags/chile.png'), name = 'Chile'},
    {img = love.graphics.newImage('flags/china.png'), name = 'China'},
    {img = love.graphics.newImage('flags/cotedivoire.png'), name = "Côte d'Ivoire"},
    {img = love.graphics.newImage('flags/croatia.png'), name = 'Croatia'},
    {img = love.graphics.newImage('flags/cuba.png'), name = 'Cuba'},
    {img = love.graphics.newImage('flags/cyprus.png'), name = 'Cyprus'},
    {img = love.graphics.newImage('flags/czechia.png'), name = 'Czechia'},
    {img = love.graphics.newImage('flags/denmark.png'), name = 'Denmark'},
    {img = love.graphics.newImage('flags/djibouti.png'), name = 'Djibouti'},
    {img = love.graphics.newImage('flags/dominica.png'), name = 'Dominica'},
    {img = love.graphics.newImage('flags/dominicanrepublic.png'), name = 'Dominican Republic'},
    {img = love.graphics.newImage('flags/drc.png'), name = 'Democratic Republic of the Congo'},
    {img = love.graphics.newImage('flags/ecuador.png'), name = 'Ecuador'},
    {img = love.graphics.newImage('flags/egypt.png'), name = 'Egypt'},
    {img = love.graphics.newImage('flags/elsalvador.png'), name = 'El Salvador'},
    {img = love.graphics.newImage('flags/equatorialguinea.png'), name = 'Equatorial Guinea'},
    {img = love.graphics.newImage('flags/eritrea.png'), name = 'Eritrea'},
    {img = love.graphics.newImage('flags/estonia.png'), name = 'Estonia'},
    {img = love.graphics.newImage('flags/eswatini.png'), name = 'Eswatini'},
    {img = love.graphics.newImage('flags/ethiopia.png'), name = 'Ethiopia'},
    {img = love.graphics.newImage('flags/fiji.png'), name = 'Fiji'},
    {img = love.graphics.newImage('flags/finland.png'), name = 'Finland'},
    {img = love.graphics.newImage('flags/france.png'), name = 'France'},
    {img = love.graphics.newImage('flags/gabon.png'), name = 'Gabon'},
    {img = love.graphics.newImage('flags/gambia.png'), name = 'Gambia'},
    {img = love.graphics.newImage('flags/georgia.png'), name = 'Georgia'},
    {img = love.graphics.newImage('flags/germany.png'), name = 'Germany'},
    {img = love.graphics.newImage('flags/ghana.png'), name = 'Ghana'},
    {img = love.graphics.newImage('flags/greece.png'), name = 'Greece'},
    {img = love.graphics.newImage('flags/grenada.png'), name = 'Grenada'},
    {img = love.graphics.newImage('flags/guatemala.png'), name = 'Guatemala'},
    {img = love.graphics.newImage('flags/guinea.png'), name = 'Guinea'},
    {img = love.graphics.newImage('flags/guineabissau.png'), name = 'Guinea-Bissau'},
    {img = love.graphics.newImage('flags/guyana.png'), name = 'Guyana'},
    {img = love.graphics.newImage('flags/haiti.png'), name = 'Haiti'},
    {img = love.graphics.newImage('flags/honduras.png'), name = 'Honduras'},
    {img = love.graphics.newImage('flags/hungary.png'), name = 'Hungary'},
    {img = love.graphics.newImage('flags/iceland.png'), name = 'Iceland'},
    {img = love.graphics.newImage('flags/india.png'), name = 'India'},
    {img = love.graphics.newImage('flags/indonesia.png'), name = 'Indonesia'},
    {img = love.graphics.newImage('flags/iran.png'), name = 'Iran'},
    {img = love.graphics.newImage('flags/iraq.png'), name = 'Iraq'},
    {img = love.graphics.newImage('flags/ireland.png'), name = 'Ireland'},
    {img = love.graphics.newImage('flags/israel.png'), name = 'Israel'},
    {img = love.graphics.newImage('flags/italy.png'), name = 'Italy'},
    {img = love.graphics.newImage('flags/jamaica.png'), name = 'Jamaica'},
    {img = love.graphics.newImage('flags/japan.png'), name = 'Japan'},
    {img = love.graphics.newImage('flags/jordan.png'), name = 'Jordan'},
    {img = love.graphics.newImage('flags/kenya.png'), name = 'Kenya'},
    {img = love.graphics.newImage('flags/kiribati.png'), name = 'Kiribati'},
    {img = love.graphics.newImage('flags/kosovo.png'), name = 'Kosovo'},
    {img = love.graphics.newImage('flags/kuwait.png'), name = 'Kuwait'},
    {img = love.graphics.newImage('flags/kyrgyzstan.png'), name = 'Kyrgyzstan'},
    {img = love.graphics.newImage('flags/laos.png'), name = 'Laos'},
    {img = love.graphics.newImage('flags/latvia.png'), name = 'Latvia'},
    {img = love.graphics.newImage('flags/lebanon.png'), name = 'Lebanon'},
    {img = love.graphics.newImage('flags/lesotho.png'), name = 'Lesotho'},
    {img = love.graphics.newImage('flags/liberia.png'), name = 'Liberia'},
    {img = love.graphics.newImage('flags/libya.png'), name = 'Libya'},
    {img = love.graphics.newImage('flags/liechtenstein.png'), name = 'Liechtenstein'},
    {img = love.graphics.newImage('flags/lithuania.png'), name = 'Lithuania'},
    {img = love.graphics.newImage('flags/luxembourg.png'), name = 'Luxembourg'},
    {img = love.graphics.newImage('flags/madagascar.png'), name = 'Madagascar'},
    {img = love.graphics.newImage('flags/malawi.png'), name = 'Malawi'},
    {img = love.graphics.newImage('flags/malaysia.png'), name = 'Malaysia'},
    {img = love.graphics.newImage('flags/maldives.png'), name = 'Maldives'},
    {img = love.graphics.newImage('flags/mali.png'), name = 'Mali'},
    {img = love.graphics.newImage('flags/malta.png'), name = 'Malta'},
    {img = love.graphics.newImage('flags/marshallislands.png'), name = 'Marshall Islands'},
    {img = love.graphics.newImage('flags/mauritania.png'), name = 'Mauritania'},
    {img = love.graphics.newImage('flags/mauritius.png'), name = 'Mauritius'},
    {img = love.graphics.newImage('flags/mexico.png'), name = 'Mexico'},
    {img = love.graphics.newImage('flags/micronesia.png'), name = 'Micronesia'},
    {img = love.graphics.newImage('flags/moldova.png'), name = 'Moldova'},
    {img = love.graphics.newImage('flags/monaco.png'), name = 'Monaco'},
    {img = love.graphics.newImage('flags/mongolia.png'), name = 'Mongolia'},
    {img = love.graphics.newImage('flags/montenegro.png'), name = 'Montenegro'},
    {img = love.graphics.newImage('flags/morocco.png'), name = 'Morocco'},
    {img = love.graphics.newImage('flags/mozambique.png'), name = 'Mozambique'},
    {img = love.graphics.newImage('flags/myanmar.png'), name = 'Myanmar'},
    {img = love.graphics.newImage('flags/namibia.png'), name = 'Namibia'},
    {img = love.graphics.newImage('flags/nauru.png'), name = 'Nauru'},
    {img = love.graphics.newImage('flags/nepal.png'), name = 'Nepal'},
    {img = love.graphics.newImage('flags/netherlands.png'), name = 'Netherlands'},
    {img = love.graphics.newImage('flags/newzealand.png'), name = 'New Zealand'},
    {img = love.graphics.newImage('flags/nicaragua.png'), name = 'Nicaragua'},
    {img = love.graphics.newImage('flags/niger.png'), name = 'Niger'},
    {img = love.graphics.newImage('flags/nigeria.png'), name = 'Nigeria'},
    {img = love.graphics.newImage('flags/northkorea.png'), name = 'North Korea'},
    {img = love.graphics.newImage('flags/northmacedonia.png'), name = 'North Macedonia'},
    {img = love.graphics.newImage('flags/norway.png'), name = 'Norway'},
    {img = love.graphics.newImage('flags/oman.png'), name = 'Oman'},
    {img = love.graphics.newImage('flags/pakistan.png'), name = 'Pakistan'},
    {img = love.graphics.newImage('flags/palau.png'), name = 'Palau'},
    {img = love.graphics.newImage('flags/palestine.png'), name = 'Palestine'},
    {img = love.graphics.newImage('flags/panama.png'), name = 'Panama'},
    {img = love.graphics.newImage('flags/papuanewguinea.png'), name = 'Papua New Guinea'},
    {img = love.graphics.newImage('flags/paraguay.png'), name = 'Paraguay'},
    {img = love.graphics.newImage('flags/peru.png'), name = 'Peru'},
    {img = love.graphics.newImage('flags/philippines.png'), name = 'Philippines'},
    {img = love.graphics.newImage('flags/poland.png'), name = 'Poland'},
    {img = love.graphics.newImage('flags/portugal.png'), name = 'Portugal'},
    {img = love.graphics.newImage('flags/qatar.png'), name = 'Qatar'},
    {img = love.graphics.newImage('flags/romania.png'), name = 'Romania'},
    {img = love.graphics.newImage('flags/russia.png'), name = 'Russia'},
    {img = love.graphics.newImage('flags/rwanda.png'), name = 'Rwanda'},
    {img = love.graphics.newImage('flags/saintlucia.png'), name = 'Saint Lucia'},
    {img = love.graphics.newImage('flags/samoa.png'), name = 'Samoa'},
    {img = love.graphics.newImage('flags/sanmarino.png'), name = 'San Marino'},
    {img = love.graphics.newImage('flags/saotomeandprincipe.png'), name = 'São Tomé and Príncipe'},
    {img = love.graphics.newImage('flags/saudiarabia.png'), name = 'Saudi Arabia'},
    {img = love.graphics.newImage('flags/senegal.png'), name = 'Senegal'},
    {img = love.graphics.newImage('flags/serbia.png'), name = 'Serbia'},
    {img = love.graphics.newImage('flags/seychelles.png'), name = 'Seychelles'},
    {img = love.graphics.newImage('flags/sierraleone.png'), name = 'Sierra Leone'},
    {img = love.graphics.newImage('flags/singapore.png'), name = 'Singapore'},
    {img = love.graphics.newImage('flags/slovakia.png'), name = 'Slovakia'},
    {img = love.graphics.newImage('flags/slovenia.png'), name = 'Slovenia'},
    {img = love.graphics.newImage('flags/solomonislands.png'), name = 'Solomon Islands'},
    {img = love.graphics.newImage('flags/somalia.png'), name = 'Somalia'},
    {img = love.graphics.newImage('flags/southafrica.png'), name = 'South Africa'},
    {img = love.graphics.newImage('flags/southkorea.png'), name = 'South Korea'},
    {img = love.graphics.newImage('flags/southsudan.png'), name = 'South Sudan'},
    {img = love.graphics.newImage('flags/spain.png'), name = 'Spain'},
    {img = love.graphics.newImage('flags/srilanka.png'), name = 'Sri Lanka'},
    {img = love.graphics.newImage('flags/stkittsandnevis.png'), name = 'Saint Kitts and Nevis'},
    {img = love.graphics.newImage('flags/stvincentandthegrenadines.png'), name = 'Saint Vincent and the Grenadines'},
    {img = love.graphics.newImage('flags/sudan.png'), name = 'Sudan'},
    {img = love.graphics.newImage('flags/suriname.png'), name = 'Suriname'},
    {img = love.graphics.newImage('flags/sweden.png'), name = 'Sweden'},
    {img = love.graphics.newImage('flags/switzerland.png'), name = 'Switzerland'},
    {img = love.graphics.newImage('flags/syria.png'), name = 'Syria'},
    {img = love.graphics.newImage('flags/taiwan.png'), name = 'Taiwan'},
    {img = love.graphics.newImage('flags/tajikistan.png'), name = 'Tajikistan'},
    {img = love.graphics.newImage('flags/tanzania.png'), name = 'Tanzania'},
    {img = love.graphics.newImage('flags/thailand.png'), name = 'Thailand'},
    {img = love.graphics.newImage('flags/timorleste.png'), name = 'Timor-Leste'},
    {img = love.graphics.newImage('flags/togo.png'), name = 'Togo'},
    {img = love.graphics.newImage('flags/tonga.png'), name = 'Tonga'},
    {img = love.graphics.newImage('flags/trinidadandtobago.png'), name = 'Trinidad and Tobago'},
    {img = love.graphics.newImage('flags/tunisia.png'), name = 'Tunisia'},
    {img = love.graphics.newImage('flags/turkey.png'), name = 'Turkey'},
    {img = love.graphics.newImage('flags/turkmenistan.png'), name = 'Turkmenistan'},
    {img = love.graphics.newImage('flags/tuvalu.png'), name = 'Tuvalu'},
    {img = love.graphics.newImage('flags/uganda.png'), name = 'Uganda'},
    {img = love.graphics.newImage('flags/ukraine.png'), name = 'Ukraine'},
    {img = love.graphics.newImage('flags/unitedarabemirates.png'), name = 'United Arab Emirates'},
    {img = love.graphics.newImage('flags/unitedkingdom.png'), name = 'United Kingdom'},
    {img = love.graphics.newImage('flags/uruguay.png'), name = 'Uruguay'},
    {img = love.graphics.newImage('flags/usa.png'), name = 'United States'},
    {img = love.graphics.newImage('flags/uzbekistan.png'), name = 'Uzbekistan'},
    {img = love.graphics.newImage('flags/vaticancity.png'), name = 'Vatican City'},
    {img = love.graphics.newImage('flags/vanuatu.png'), name = 'Vanuatu'},
    {img = love.graphics.newImage('flags/venezuela.png'), name = 'Venezuela'},
    {img = love.graphics.newImage('flags/vietnam.png'), name = 'Vietnam'},
    {img = love.graphics.newImage('flags/yemen.png'), name = 'Yemen'},
    {img = love.graphics.newImage('flags/zambia.png'), name = 'Zambia'},
    {img = love.graphics.newImage('flags/zimbabwe.png'), name = 'Zimbabwe'},
}

return FlagsTable